### ISSUE TITLE
Ability to pass through information for games page

### ISSUE THREAD

**Issue by Dewpg** [jp31415926/Sportacus#12]
**Is your feature request related to a problem? Please describe.**
It would be helpful to prefill the /games page through the use of the url.  Like say; https://www.sportacus.com/game/teamnameofcoach(orteam)
or /game/dates/9282021-12302021
 or accept as many arguments as wanted by appending /teamnameofcoach/daterange9282021-12312021/fieldnamedataforfield

**Describe the solution you'd like**
The above forwarding of form information from url

**Describe alternatives you've considered**
None known

**Additional context**

**Comment by jp31415926** [comment]
You can already do this (refer to GameController::parseSearchParameters)

Terms: team, sdate, edate, loc, official

Examples:
https://sportac.us/game/?team=smith&sdate=2021-08-21&edate=2021-08-21
https://sportac.us/game/?loc=palmer%202

You can also view the schedule by team ID using teamSchId=<team id>

Examples (links are on the team page at https://sportac.us/team/7670/show):
https://sportac.us/game/?teamSchId=7670
https://sportac.us/game/offsch/?teamSchId=7670

**Comment by Dewpg** [comment]
https://github.com/jp31415926/Sportacus/blob/1afc3f80c1f07757c36a4fcf244c16ffe0612b1a/src/Scheduler/SchBundle/Controller/GameController.php  Right you are.  Thanks.
